headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\Desktop\\Emarson frontend\\epdg\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\User\\Desktop\\Emarson frontend\\epdg"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"
VITE_API_URL = "https://backend-productionepdg.up.railway.app"
VITE_MOCK_AUTH = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/api/*"
to = "https://backend-productionepdg.up.railway.app/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]