plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\Desktop\\Emarson frontend\\EPDG-Landing-Page\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\User\\Desktop\\Emarson frontend\\EPDG-Landing-Page"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]