-- Reconcile the live lead pipeline without exposing prospect data to browser users.
-- This migration is idempotent and intentionally replaces the overly broad legacy policies.

create schema if not exists private;

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  first_name text,
  last_name text,
  full_name text,
  email text not null,
  phone text,
  message text,
  service_interest text,
  urgency text,
  intent_description text,
  track_interest text,
  division text,
  division_label text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

drop policy if exists allow_insert on public.leads;
drop policy if exists allow_authenticated_read on public.leads;

revoke all on table public.leads from anon, authenticated;
grant select, insert, update, delete on table public.leads to service_role;

create index if not exists idx_leads_created_at
  on public.leads (created_at desc);
create index if not exists idx_leads_status_created_at
  on public.leads (status, created_at desc);

create table if not exists private.lead_rate_limits (
  id bigint generated by default as identity primary key,
  requester_hash text not null,
  requested_at timestamptz not null default now()
);

create index if not exists idx_lead_rate_limits_requester_time
  on private.lead_rate_limits (requester_hash, requested_at desc);

alter table private.lead_rate_limits enable row level security;
revoke all on table private.lead_rate_limits from public, anon, authenticated;
grant select, insert, delete on table private.lead_rate_limits to service_role;
grant usage, select on sequence private.lead_rate_limits_id_seq to service_role;

create or replace function public.check_lead_rate_limit(
  request_hash text,
  max_requests integer default 5,
  window_minutes integer default 15
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_count integer;
begin
  if request_hash is null or length(request_hash) < 16 then
    return false;
  end if;

  delete from private.lead_rate_limits
  where requested_at < now() - interval '24 hours';

  select count(*)
    into recent_count
  from private.lead_rate_limits
  where requester_hash = request_hash
    and requested_at >= now() - make_interval(mins => greatest(window_minutes, 1));

  if recent_count >= greatest(max_requests, 1) then
    return false;
  end if;

  insert into private.lead_rate_limits (requester_hash)
  values (request_hash);

  return true;
end;
$$;

revoke execute on function public.check_lead_rate_limit(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.check_lead_rate_limit(text, integer, integer)
  to service_role;
